
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Hamburger from './components/hamburger'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {


	return (
		<html lang="en">
			<body className={inter.className}>

				<Hamburger />


				{/* <nav>
					<Link className="links" href="#">
						Home
					</Link>
					<Link className="links" href="/swipe-north">
						Jobb api
					</Link>
					<Link className="links" href="/skelleftea">
						Skellefteå
					</Link>
					<Link className="links" href="/profile">
						Profile
					</Link>
					<Link className="links" href="/matched-jobs">
						Matched jobs
					</Link>
					<Link className="links" href="/login">
						Log in
					</Link>
				</nav> */}

				<main>{children}</main>
			</body>
		</html>
	)
}
