import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main>
					<h1>Root Layout</h1>
					<Link className="links" href="#">
						Home
					</Link>
					<Link className="links" href="/about">
						About
					</Link>
					<Link className="links" href="/profile">
						Profile
					</Link>
					<Link className="links" href="/matched-jobs">
						Matched jobs
					</Link>
					<Link className="links" href="/login">
						Log in
					</Link>
				</main>
				{children}
			</body>
		</html>
	)
}
